#!/usr/bin/env bash
set -Eeuo pipefail

REPO_DEFAULT="Chemically-Motivated-Solutions/ScopeVault"
DIST_DIR_DEFAULT="dist"
NOTES_FILE_DEFAULT="release-notes.md"
API_VERSION_DEFAULT="2022-11-28"

REPO="${REPO:-$REPO_DEFAULT}"
DIST_DIR="${DIST_DIR:-$DIST_DIR_DEFAULT}"
NOTES_FILE="${NOTES_FILE:-$NOTES_FILE_DEFAULT}"
API_VERSION="${API_VERSION:-$API_VERSION_DEFAULT}"

TAG="${TAG:-}"
TARGET_COMMIT="${TARGET_COMMIT:-}"
TITLE="${TITLE:-}"
DRAFT="${DRAFT:-false}"
GENERATE_NOTES="${GENERATE_NOTES:-false}"
LATEST="${LATEST:-true}"
VERIFY_DOWNLOAD="${VERIFY_DOWNLOAD:-false}"
SKIP_TAG_PUSH="${SKIP_TAG_PUSH:-false}"
SKIP_CLEAN_TREE_CHECK="${SKIP_CLEAN_TREE_CHECK:-false}"
DRY_RUN="${DRY_RUN:-false}"
BUILD_CMD="${BUILD_CMD:-}"
INCLUDE_SOURCE_BUNDLE="${INCLUDE_SOURCE_BUNDLE:-true}"

WORKDIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$WORKDIR"
TMP_DIR=""
ORIGINAL_REF="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"

usage() {
  cat <<'EOF'
Usage:
  scripts/release.sh --tag v1.2.3 [options]

Options:
  --tag TAG                Release tag to create or verify. Required.
  --target-commit SHA      Commit to tag. Defaults to current HEAD.
  --title TITLE            Release title. Defaults to TAG.
  --repo OWNER/REPO        Defaults to Chemically-Motivated-Solutions/ScopeVault
  --dist-dir PATH          Defaults to dist
  --notes-file PATH        Defaults to release-notes.md
  --draft                  Create as draft release
  --publish                Create as published release
  --generate-notes         Use GitHub autogenerated release notes
  --no-generate-notes      Do not use autogenerated notes
  --latest                 Mark as latest release
  --not-latest             Do not mark as latest release
  --verify-download        Download published assets into a temp dir for verification
  --skip-tag-push          Do not push tag to origin
  --skip-clean-tree-check  Allow dirty working tree
  --dry-run                Print actions without mutating remote state
  -h, --help               Show help

Environment overrides:
  REPO, DIST_DIR, NOTES_FILE, API_VERSION, TAG, TARGET_COMMIT, TITLE,
  DRAFT, GENERATE_NOTES, LATEST, VERIFY_DOWNLOAD, SKIP_TAG_PUSH,
  SKIP_CLEAN_TREE_CHECK, DRY_RUN, BUILD_CMD, INCLUDE_SOURCE_BUNDLE

Examples:
  scripts/release.sh --tag v0.1.0 --draft
  scripts/release.sh --tag v0.1.0 --publish --notes-file release-notes.md
  TAG=v0.1.0 GENERATE_NOTES=true scripts/release.sh
  TAG=v0.1.0 BUILD_CMD='python -m compileall cli.py' scripts/release.sh
EOF
}

log() {
  printf '[release] %s\n' "$*"
}

die() {
  printf '[release] ERROR: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  local exit_code=$?
  if [[ -n "${TMP_DIR:-}" && -d "${TMP_DIR:-}" ]]; then
    rm -rf "$TMP_DIR"
  fi
  if [[ -n "${ORIGINAL_REF:-}" ]]; then
    git checkout -q "$ORIGINAL_REF" >/dev/null 2>&1 || true
  fi
  if [[ $exit_code -ne 0 ]]; then
    printf '[release] FAILED with exit code %s\n' "$exit_code" >&2
  fi
  exit "$exit_code"
}

trap cleanup EXIT
trap 'die "line $LINENO: command failed: $BASH_COMMAND"' ERR

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

run() {
  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] '
    printf '%q ' "$@"
    printf '\n'
  else
    "$@"
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tag) TAG="${2:?missing value for --tag}"; shift 2 ;;
      --target-commit) TARGET_COMMIT="${2:?missing value for --target-commit}"; shift 2 ;;
      --title) TITLE="${2:?missing value for --title}"; shift 2 ;;
      --repo) REPO="${2:?missing value for --repo}"; shift 2 ;;
      --dist-dir) DIST_DIR="${2:?missing value for --dist-dir}"; shift 2 ;;
      --notes-file) NOTES_FILE="${2:?missing value for --notes-file}"; shift 2 ;;
      --draft) DRAFT="true"; shift ;;
      --publish) DRAFT="false"; shift ;;
      --generate-notes) GENERATE_NOTES="true"; shift ;;
      --no-generate-notes) GENERATE_NOTES="false"; shift ;;
      --latest) LATEST="true"; shift ;;
      --not-latest) LATEST="false"; shift ;;
      --verify-download) VERIFY_DOWNLOAD="true"; shift ;;
      --skip-tag-push) SKIP_TAG_PUSH="true"; shift ;;
      --skip-clean-tree-check) SKIP_CLEAN_TREE_CHECK="true"; shift ;;
      --dry-run) DRY_RUN="true"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) die "unknown argument: $1" ;;
    esac
  done
}

ensure_repo_context() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "run this script inside the repository"
  local current_remote
  current_remote="$(git remote get-url origin 2>/dev/null || true)"
  if [[ -z "$current_remote" ]]; then
    die "origin remote is not configured"
  fi
  if [[ "$current_remote" != *"$REPO"* ]]; then
    log "warning: origin remote does not appear to match '$REPO': $current_remote"
  fi
}

check_prereqs() {
  require_cmd git
  require_cmd gh
  require_cmd jq
  require_cmd sha256sum
  gh auth status >/dev/null 2>&1 || die "GitHub CLI is not authenticated"
}

check_working_tree() {
  if [[ "$SKIP_CLEAN_TREE_CHECK" == "true" ]]; then
    return
  fi
  [[ -z "$(git status --porcelain)" ]] || die "working tree is dirty; commit or stash changes first"
}

resolve_target_commit() {
  if [[ -z "$TARGET_COMMIT" ]]; then
    TARGET_COMMIT="$(git rev-parse HEAD)"
  fi
  git rev-parse --verify "$TARGET_COMMIT^{commit}" >/dev/null
  if [[ -z "$TITLE" ]]; then
    TITLE="$TAG"
  fi
}

ensure_tag() {
  if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
    local existing_commit
    existing_commit="$(git rev-list -n 1 "$TAG")"
    [[ "$existing_commit" == "$TARGET_COMMIT" ]] || die "existing tag $TAG points to $existing_commit, expected $TARGET_COMMIT"
    log "tag $TAG already exists at $existing_commit"
  else
    run git tag -a "$TAG" "$TARGET_COMMIT" -m "Release $TAG"
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
      log "would create tag $TAG at $TARGET_COMMIT (dry-run)"
    else
      log "created tag $TAG at $TARGET_COMMIT"
    fi
  fi

  if [[ "$SKIP_TAG_PUSH" != "true" ]]; then
    run git push origin "$TAG"
  fi
}

prepare_dist() {
  mkdir -p "$DIST_DIR"
  run git checkout "$TAG"

  if [[ -n "$BUILD_CMD" ]]; then
    log "running build command"
    if [[ "$DRY_RUN" == "true" ]]; then
      printf '[dry-run] %s\n' "$BUILD_CMD"
    else
      eval "$BUILD_CMD"
    fi
  fi

  if [[ "$INCLUDE_SOURCE_BUNDLE" == "true" ]]; then
    local bundle
    bundle="$DIST_DIR/scopevault-${TAG#v}-source.tar.gz"
    if [[ "$DRY_RUN" == "true" ]]; then
      printf '[dry-run] git archive --format=tar.gz --output=%q %q\n' "$bundle" "$TAG"
    else
      git archive --format=tar.gz --output="$bundle" "$TAG"
    fi
  fi

  shopt -s nullglob
  local assets=("$DIST_DIR"/*)
  shopt -u nullglob
  [[ ${#assets[@]} -gt 0 ]] || die "no release assets found in $DIST_DIR"

  if [[ "$DRY_RUN" != "true" ]]; then
    local too_large_count
    too_large_count="$(find "$DIST_DIR" -maxdepth 1 -type f -size +2G | wc -l | tr -d ' ')"
    [[ "$too_large_count" == "0" ]] || die "one or more assets exceed GitHub's 2 GiB per-asset limit"
  fi
}

write_checksums() {
  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] write checksums in %q\n' "$DIST_DIR/SHA256SUMS.txt"
    return
  fi

  (
    cd "$DIST_DIR"
    rm -f SHA256SUMS.txt
    local files=()
    shopt -s nullglob
    for f in *; do
      [[ -f "$f" ]] || continue
      [[ "$f" == "SHA256SUMS.txt" ]] && continue
      files+=("$f")
    done
    shopt -u nullglob
    [[ ${#files[@]} -gt 0 ]] || die "no files available for checksum generation in $DIST_DIR"
    sha256sum "${files[@]}" > SHA256SUMS.txt
  )
}

validate_notes() {
  if [[ "$GENERATE_NOTES" == "true" ]]; then
    return
  fi
  [[ -f "$NOTES_FILE" ]] || die "notes file not found: $NOTES_FILE"
}

create_release() {
  local args=()
  args+=(release create "$TAG")
  args+=(--repo "$REPO")
  args+=(--title "$TITLE")

  if [[ "$GENERATE_NOTES" == "true" ]]; then
    args+=(--generate-notes)
  else
    args+=(--notes-file "$NOTES_FILE")
  fi

  if [[ "$DRAFT" == "true" ]]; then
    args+=(--draft)
  fi

  if [[ "$LATEST" == "true" ]]; then
    args+=(--latest)
  elif [[ "$LATEST" == "false" ]]; then
    args+=(--latest=false)
  fi

  local assets=()
  mapfile -t assets < <(find "$DIST_DIR" -maxdepth 1 -type f -print | sort)
  [[ "${#assets[@]}" -gt 0 ]] || die "no assets found in dist dir: $DIST_DIR"
  args+=("${assets[@]}")

  run gh "${args[@]}"
}

fetch_release_json() {
  gh api \
    -H "X-GitHub-Api-Version: $API_VERSION" \
    "/repos/$REPO/releases/tags/$TAG"
}

verify_release() {
  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] verify release via gh api for tag %q\n' "$TAG"
    return
  fi

  local release_json
  release_json="$(fetch_release_json)"

  echo "$release_json" | jq '{tag_name, name, draft, prerelease, html_url, created_at, published_at, assets: [.assets[] | {name, size, download_count, browser_download_url}]}'

  mapfile -t local_assets < <(find "$DIST_DIR" -maxdepth 1 -type f | sed 's#.*/##' | sort)
  mapfile -t remote_assets < <(echo "$release_json" | jq -r '.assets[].name' | sort)

  local local_count="${#local_assets[@]}"
  local remote_count="${#remote_assets[@]}"
  [[ "$local_count" == "$remote_count" ]] || die "asset count mismatch: local=$local_count remote=$remote_count"

  local local_joined remote_joined
  local_joined="$(printf '%s\n' "${local_assets[@]}")"
  remote_joined="$(printf '%s\n' "${remote_assets[@]}")"
  [[ "$local_joined" == "$remote_joined" ]] || die "asset name mismatch between local dist and published release"
}

verify_checksums() {
  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] verify checksums in %q\n' "$DIST_DIR"
    return
  fi
  (
    cd "$DIST_DIR"
    sha256sum -c SHA256SUMS.txt
  )
}

verify_download() {
  if [[ "$VERIFY_DOWNLOAD" != "true" ]]; then
    return
  fi

  TMP_DIR="$(mktemp -d)"
  local download_dir="$TMP_DIR/downloaded"
  mkdir -p "$download_dir"

  run gh release download "$TAG" --repo "$REPO" --dir "$download_dir"

  if [[ "$DRY_RUN" != "true" ]]; then
    local count
    count="$(find "$download_dir" -maxdepth 1 -type f | wc -l | tr -d ' ')"
    [[ "$count" -gt 0 ]] || die "download verification failed: no assets downloaded"
    log "downloaded assets into $download_dir"
  fi
}

main() {
  parse_args "$@"
  [[ -n "$TAG" ]] || die "--tag is required"

  ensure_repo_context
  check_prereqs
  check_working_tree
  resolve_target_commit

  log "repo:   $REPO"
  log "tag:    $TAG"
  log "commit: $TARGET_COMMIT"
  log "draft:  $DRAFT"

  ensure_tag
  prepare_dist
  write_checksums
  verify_checksums
  validate_notes
  create_release
  verify_release
  verify_download

  if [[ "$DRAFT" == "true" ]]; then
    log "draft release created for $TAG"
  else
    log "published release created for $TAG"
  fi
}

main "$@"
